spring.datasource.url=jdbc:postgresql://localhost:5432/chatdb
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

pinata.api.key=629fc542b5b4f23e0a02
pinata.api.secret=82d19be6413ed724d615f7f49c3d9f31383848009b5f74be3f824497781d897e
pinata.base.url=https://api.pinata.cloud/

web3.rpc.url=https://sepolia.base.org
web3.contract.address=0xC9266A970E7840c7413e030ed453AB467c57F6d5
web3.private.key=0x360305ba1a0d76d3d52446d491daba4593723839e11348ab254dce6516922265